apiVersion: v1
kind: Service
metadata:
  name: k8s-web-nginx
spec:
  type: NodePort
  selector:
    app: k8s-web-nginx
  ports:
  - port: 3333
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-web-nginx
  template:
    metadata:
      labels:
        app: k8s-web-nginx
    spec:
      containers:
      - name: k8s-web-nginx
        image: gauravjo1/k8s-web-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

